"""empty message

Revision ID: 2075585fe061
Revises: 
Create Date: 2022-08-14 13:12:43.122512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2075585fe061'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=250), nullable=True),
    sa.Column('lastname', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=250), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('email_body', sa.Text(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailing_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('crontab', sa.String(length=1000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('mailing_list', sa.Integer(), nullable=True),
    sa.Column('email_template', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['email_template'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['mailing_list'], ['mailing_list.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipients_from_mailing_list',
    sa.Column('mailing_list_id', sa.Integer(), nullable=True),
    sa.Column('recipients_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mailing_list_id'], ['mailing_list.id'], ),
    sa.ForeignKeyConstraint(['recipients_id'], ['recipients.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipients_from_mailing_list')
    op.drop_table('campaigns')
    op.drop_table('mailing_list')
    op.drop_table('emails')
    op.drop_table('recipients')
    op.drop_table('ab_user')
    # ### end Alembic commands ###
