"""empty message

Revision ID: 3cd89b67f52d
Revises: 1641d90aed60
Create Date: 2022-08-15 10:57:46.338366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd89b67f52d'
down_revision = '1641d90aed60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailing_list', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailing_list', 'is_favorite')
    # ### end Alembic commands ###
