"""empty message

Revision ID: fa1e2b050209
Revises: 3cd89b67f52d
Create Date: 2022-08-15 12:24:13.026536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1e2b050209'
down_revision = '3cd89b67f52d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    op.drop_column('mailing_list', 'is_favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailing_list', sa.Column('is_favorite', sa.BOOLEAN(), nullable=True))
    op.drop_column('emails', 'is_favorite')
    # ### end Alembic commands ###
